name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Alternativen: 'zulu', 'oracle', etc.
          java-version: '17'      # oder 21, je nach deinem Projekt

      - name: Verify Java installation
        run: java -version

      - name: Compile Java program
        run: javac HelloWorld.java

      - name: Run Java program
        run: java HelloWorld

      - name: Finish job
        run: echo "🍏 This job's status is ${{ job.status }}."
